FROM alpine:3.19
RUN addgroup -S spring && adduser -S spring -G spring
USER spring:spring
ARG JAR_FILE=target/*.jar
ARG RUNTIME_FOLDER=custom-jre
COPY ${JAR_FILE} app.jar
COPY ${RUNTIME_FOLDER} /jre
ENTRYPOINT /jre/bin/java -jar app.jar
