# This workflow will :
# - build a Java project with Maven
# - generate a runtime for our docker image using jlink
# - build the docker image
# - publish it to github

name: Java CI with Docker Alpine

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
env:
  IMAGE_NAME: jlink-img-alpine
  PLATFORM: alpine

jobs:
  build-jar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
      - name: Cache Maven deps
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - run: mkdir artifacts && cp target/*.jar artifacts
      - uses: actions/upload-artifact@v1
        with:
          name: package
          path: artifacts

  # Building our runtime (only if new)
  build-jre:
    env:
      JAVA_TARGET: /opt/jdk/jdk-17
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache runtime
        id: cache-runtime
        uses: actions/cache@v1
        with:
          path: custom-jre
          key: ${{ env.PLATFORM }}-${{ hashFiles('**/jlink-opts.txt') }}
      - name: Set up JDK 17
        if: steps.cache-runtime.outputs.cache-hit != 'true'
        uses: actions/setup-java@v3
        with:
            distribution: 'temurin'
            java-version: '17'
      # needed as Alpine is the platform we're targeting, different from the one we're building
      - name: Get Alpine JDK
        if: steps.cache-runtime.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.4.1%2B1/OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.4.1_1.tar.gz
          mkdir -p /opt/jdk && tar -xzvf OpenJDK17U-jdk_x64_alpine-linux_hotspot_17.0.4.1_1.tar.gz -C /opt/jdk/
          mv /opt/jdk/jdk-17.0.4.1+1 /opt/jdk/jdk-17
      - name: Create custom runtime
        if: steps.cache-runtime.outputs.cache-hit != 'true'
        run: jlink @jlink-opts.txt

  push:
    # Ensure build job passes before pushing image.
    needs: [build-jar, build-jre]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Download the built jar
        uses: actions/download-artifact@v4.1.7
        with:
          name: package
          path: target

      - name: Get runtime
        id: cache-runtime
        uses: actions/cache@v1
        with:
          path: custom-jre
          key: ${{ env.PLATFORM }}-${{ hashFiles('**/jlink-opts.txt') }}

      - name: Build image
        run: docker build . --file Dockerfile.alpine --tag image

      - name: Log into registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=docker.pkg.github.com/${{ github.repository }}/$IMAGE_NAME
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker tag image $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
